### ISSUE TITLE
set up CI

### ISSUE THREAD

**Issue by pjz** [gratipay/filesystem_tree.py#5]
Given filesystem munging,  Appveyor (or some other windows-based CI) would also be useful.

**Comment by whit537** [comment]
We have [CI at Travis](https://travis-ci.org/gratipay/filesystem_tree.py). +1 for Windows (~= Appveyor).

**Comment by whit537** [comment]
https://ci.appveyor.com/project/whit537/filesystem-tree-py

@pjz Want to make a PR for Appveyor config over here based on what we're doing in Aspen?

**Comment by pjz** [comment]
I could add the config file, but I don't have perms to actually have appVeyor pay attention to this repo.  You'll have to do that bit.  Which is why I left it as an issue and didn't submit a PR.

**Comment by whit537** [comment]
Sorry, I should have been more explicit: I've set up the project at AppVeyor, though the link [above](https://github.com/gratipay/filesystem_tree.py/issues/5#issuecomment-129265063) is under `whit537` and is 404 because I've [since reconfigured](https://github.com/gratipay/aspen-python/pull/482#issuecomment-129417846) for `gratipay`. Here's the new URL:

https://ci.appveyor.com/project/gratipay/filesystem-tree-py

I see an quick fail with `Specify a project or solution file. The directory does not contain a project or solution file.` That sounds like if you add the config file and push we should see a build.

**Comment by pjz** [comment]
Fixed with #14
